# These are supported funding model platforms

github: [openclaw]
patreon: openclaw
open_collective: openclaw
ko_fi: openclaw
tidelift: npm/openclaw
community_bridge: openclaw
liberapay: openclack
issuehunt: openclaw
lfx_crowdfunding: openclaw
custom: ["https://openclaw.dev/donate"]
